{"errorMessage":"An error occurred (UnrecognizedClientException) when calling the PutItem operation: The security token included in the request is invalid.","errorType":"ClientError","stackTrace":["  File \"/var/task/handler.py\", line 41, in lambda_handler\n    reported_income.put_item(Item=report.to_item())\n","  File \"/var/runtime/boto3/resources/factory.py\", line 520, in do_action\n    response = action(self, *args, **kwargs)\n","  File \"/var/runtime/boto3/resources/action.py\", line 83, in __call__\n    response = getattr(parent.meta.client, operation_name)(*args, **params)\n","  File \"/var/runtime/botocore/client.py\", line 386, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n","  File \"/var/runtime/botocore/client.py\", line 705, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}
